// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package repository

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	CreateWallet(ctx context.Context, id uuid.UUID) (Wallet, error)
	GetWallet(ctx context.Context, id uuid.UUID) (Wallet, error)
	GetWalletForUpdate(ctx context.Context, id uuid.UUID) (Wallet, error)
	UpdateWalletBalance(ctx context.Context, arg UpdateWalletBalanceParams) (Wallet, error)
}

var _ Querier = (*Queries)(nil)
